project_id = "ahwhtxygyzoadsmdrwwg"

[functions.places-geocode]
verify_jwt = false

[functions.places-autocomplete]
verify_jwt = false

[functions.places-details]
verify_jwt = false

[functions.weather-current]
verify_jwt = false

[functions.get-weather-google]
verify_jwt = false

[functions.get-weather]
verify_jwt = false

[functions.delete-user-complete]
verify_jwt = true

[functions.maps-key]
verify_jwt = false

