project_id = "ahwhtxygyzoadsmdrwwg"

[functions.admin-user-management]
verify_jwt = true

[functions.places-geocode]
verify_jwt = true

[functions.places-autocomplete]
verify_jwt = true

[functions.places-details]
verify_jwt = true

[functions.weather-current]
verify_jwt = true

[functions.get-weather-google]
verify_jwt = true

[functions.get-weather]
verify_jwt = true

[functions.delete-user-complete]
verify_jwt = true

[functions.maps-key]
verify_jwt = true

[functions.send-email]
verify_jwt = true

[functions.ai-chat]
verify_jwt = true
